apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redisslave-replicaset
  labels:
    app: redis
    role: slave
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - name: redis-slave
        image: k8s.gcr.io/redis-slave:v2
        ports:
        - name: redis-server
          containerPort: 6379