apiVersion: v1
kind: Service
metadata:
  name: redismaster-service
  labels:
    app: redis
    role: master
spec:
  selector:
    app: redis
    role: master
  ports:
  - port: 6379
    targetPort: redis-server