apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-replicaset
  labels:
    app: redis
    role: master
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: redis-master
        image: redis:2.8.23
        ports:
        - name: redis-server
          containerPort: 6379